### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json
{
    "email": "ds785@gmail.com",
    "password": "stothed"
}

### Find a particular user with a given id
GET http://localhost:3000/auth/1

### Find all user with a given email
GET http://localhost:3000/auth/email=
### Delete a user with a given email
DELETE http://localhost:3000/auth/auth/1

### Update a user
PATCH http://localhost:3000/auth/auth/1
